name: Testing on push

on: push

jobs:
  test:
    name: Test passes
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Install modules
        run: npm ci

      - name: Testing
        run: npm test
        env:
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SUPABASE_BUCKET: ${{ secrets.AUTH_SECRET }}
